### ISSUE TITLE
NullPointerException when src/build/java does not exist

### ISSUE THREAD

**Issue by fxbonnet** [fxbonnet/builder#2]

**Comment by rmannibucau** [comment]
Hello

Any hope to see it fixed and released?

It is just a null check on https://github.com/javabuild/builder-maven-plugin/blob/master/src/main/java/net/java/javabuild/ExecuteMojo.java#L159 AFAIK

**Comment by fxbonnet** [comment]
Hello,
I have been very busy lately. Is this issue blocking for you?

**Comment by rmannibucau** [comment]
No more - migrated to exec-mvn-plugin in the meantime - but multimodule support would be awesome

**Comment by fxbonnet** [comment]
Fixed in trunk
